apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  labels:
    app: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: rabbitmq-consumer
        image: natriosg/notificacao:latest
        imagePullPolicy: Always
        env:
        # Configuração do RabbitMQ
        - name: RabbitMQHost
          value: "rabbitmq-service.default.svc.cluster.local"
        - name: RabbitMQUser
          value: "guest"
        - name: RabbitMQPassword
          value: "guest"

      

        # Configuração da API MailerSend
        - name: MAILERSEND_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: mailersend-secret
              key: token
