apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  SMTP_USER: TVNfeThCeVNpQHRyaWFsLW82NXFuZ2tuM3BkZ3dyMTIubWxzZW5kZXIubmV0
  SMTP_PASSWORD: bXNzcC5lSE5Pa1ZiLmp5N3pwbDkzNWpwbDV2eDYuQTJseXJIOA==
